name: selcukaiassistant
description: SelcukAiAssistant
publish_to: 'none'
version:  1.0.2+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  appwrite: 20.3.2
  cupertino_icons: ^1.0.8
  easy_audience_network: ^0.0.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_dotenv: ^6.0.0
  flutter_highlight: ^0.7.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown_plus: ^1.0.5
  flutter_secure_storage: ^9.2.2
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.1.2
  markdown: ^7.3.0
  path_provider: ^2.1.3
  permission_handler: ^12.0.1
  share_plus: ^10.1.3
  speech_to_text: ^7.0.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.5
  flutter_test: 
    sdk: flutter
  hive_generator: ^2.0.1
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: SourceSans3
      fonts:
        - asset: "assets/fonts/source_sans_3/SourceSans3[wght].ttf"
    - family: SourceSerif4
      fonts:
        - asset: "assets/fonts/source_serif_4/SourceSerif4[opsz,wght].ttf"
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
    - family: NotoSansSymbols
      fonts:
        - asset: assets/fonts/noto_sans_symbols/NotoSansSymbols-wght.ttf
    - family: NotoSansSymbols2
      fonts:
        - asset: assets/fonts/noto_sans_symbols2/NotoSansSymbols2-Regular.ttf

  assets:
    - assets/images/
    - assets/lottie/
    - assets/branding/
    - .env

flutter_native_splash:
  color: "#F7F7F5"
  color_dark: "#101010"
  image: "assets/branding/selcuk_seal.jpg"
  image_dark: "assets/branding/selcuk_seal.jpg"
  android_12:
    color: "#F7F7F5"
    color_dark: "#101010"
    image: "assets/branding/selcuk_seal.jpg"
    image_dark: "assets/branding/selcuk_seal.jpg"

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/branding/selcuk_seal.jpg"
  adaptive_icon_background: "#F7F7F5"
  adaptive_icon_foreground: "assets/branding/selcuk_seal.jpg"
