name: selcukaiassistant
description: SelcukAiAssistant
publish_to: 'none'
version:  1.0.2+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  appwrite: 20.3.2
  cupertino_icons: ^1.0.8
  easy_audience_network: ^0.0.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_dotenv: ^6.0.0
  flutter_markdown_plus: ^1.0.5
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.1.2
  path_provider: ^2.1.3
  permission_handler: ^12.0.1
  share_plus: ^10.1.3
  speech_to_text: ^7.0.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  flutter_test: 
    sdk: flutter
  hive_generator: ^2.0.1
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - .env
